### SERVER SETTINGS ###
server:
  port: 8080

### H2 DATABASE & APP SETTINGS ###
spring:
  datasource:
    url: jdbc:h2:file:C:/Users/kkoumagna/tmp/contacts
    driverClassName: org.h2.Driver
    username: user
    password: userpw
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

### SWAGGER SETTINGS ###
swagger:
  api:
    info:
      title: TODO REST API
      description: Todo app Rest Api
      version: 0.1
      contact-name: Kokou KOUMAGNA
      contact-email: kokou.koumagnagottoh@gmail.com
      host-name: localhost:8080
